# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"

  lane :build_test_apps do
    clean_test_apps_build_dir

    build_time_start = DateTime.now

    build_test_app(test_app: "TestApp", output_dir: "TestApp")
  end

  lane :clean_test_apps_build_dir do
    sh "rm -rf ../build/*"
  end
end
