platform :ios, '10.0'

	target 'TestApp' do
		rn_path = '../node_modules/react-native'
	
		pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
		pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
		pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"
		pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/GLog.podspec"
		pod 'React', path: rn_path, subspecs: [
			'Core',
			'CxxBridge',
			'RCTAnimation',
			'RCTActionSheet',
			'RCTImage',
			'RCTLinkingIOS',
			'RCTNetwork',
			'RCTSettings',
			'RCTText',
			'RCTVibration',
			'RCTWebSocket',
			'RCTPushNotification',
			'RCTCameraRoll',
			'RCTSettings',
			'RCTBlob',
			'RCTGeolocation',
			'DevSupport'
		]
	
		pod 'react-native-klarna-inapp-sdk', :path => '../../react-native-klarna-inapp-sdk.podspec'
	end

	post_install do |installer|
        installer.pods_project.targets.each do |target|

            # The following is needed to ensure the "archive" step works in XCode.
            # It removes React & Yoga from the Pods project, as it is already included in the main project.
            # Without this, you'd see errors when you archive like:
            # "Multiple commands produce ... libReact.a"
            # "Multiple commands produce ... libyoga.a"

            targets_to_ignore = %w(React yoga)

            if targets_to_ignore.include? target.name
                target.remove_from_project
            end

        end
    end
