name: Prepare iOS
description: Prepare iOS environment

runs:
  using: composite
  steps:
    - name: Cache Pods
      uses: actions/cache@v4
      with:
        path: |
          ios/Pods
          TestApp/ios/Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
