name: Prepare iOS
description: Prepare iOS environment

runs:
  using: composite
  steps:
    - name: Select Xcode
      shell: bash
      run: |
        sudo xcode-select -s /Applications/Xcode_26.0.1.app
        xcodebuild -version
    - name: Cache Pods
      uses: actions/cache@v4
      with:
        path: |
          TestApp/ios/Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
