def find_and_replace_boost_url
  pod_spec = "../node_modules/react-native/third-party-podspecs/boost.podspec"
  puts "Debug: Starting boost URL replacement"
  if File.exist?(pod_spec)
    puts "Debug: Found boost.podspec"
    spec_content = File.read(pod_spec)
    spec_content.gsub!(
      'https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.bz2',
      'https://archives.boost.io/release/1.76.0/source/boost_1_76_0.tar.bz2'
    )
    File.write(pod_spec, spec_content)
    puts "Debug: Updated boost.podspec"
  end
end

# Let the magic happen!
find_and_replace_boost_url

# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'

prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'RNKlarnaMobileSDK' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for RNKlarnaMobileSDK
  pod 'KlarnaMobileSDK', '2.9.0'

  target 'RNKlarnaMobileSDKTests' do
    # Pods for testing
    pod 'OCMock'
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
