# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"

  lane :run_lib_tests do
    clean_lib_build_dir

    run_tests(workspace: "ios/KlarnaInAppSDK.xcworkspace",
        output_directory: "build/KlarnaInAppSDK",
        scheme: "KlarnaInAppSDK")
  end

  lane :clean_lib_build_dir do
    sh "rm -rf build/*"
  end

  lane :build_test_apps do
    clean_test_apps_build_dir

    build_time_start = DateTime.now

    xcversion(version: ">= 12.1")
    gym(
      workspace: "TestApp/ios/TestApp.xcworkspace",
      scheme: "TestApp",
      clean: true,
      output_directory: "TestApp/build/",
      configuration: "Release",
      export_method: "enterprise",
    )
  end

  lane :clean_test_apps_build_dir do
    sh "rm -rf TestApp/build/*"
  end
end
